apiVersion: v1
kind: Secret
metadata:
  name: egar-secret
type: Opaque
data:
  dbuser: xxxx
  dbpass: xxxxxxxxxxxxxx
  cbpuser: xxxxxxxxxxxxxxxxxxxxxxx
  cbppass: xxxxxxxxxxxxxxxxxxxxxx
  clientid: xxxxxxxxxxxxxxxxxxx
  clientsecret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  enckey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
